name       : perl-locale-codes
version    : '3.72'
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/S/SB/SBECK/Locale-Codes-3.72.tar.gz : 5859c087d6f977ee237bc762396adb352b9732d325ccbd2cecacdad63e2f1320
homepage   : https://metacpan.org/pod/Locale::Codes
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Locale::Language - module for dealing with language code sets
description: |
    Locale-Codes is a distribution containing a set of modules designed to work with sets of codes which uniquely identify something. For example, there are codes associated with different countries, different currencies, different languages, etc. These sets of codes are typically maintained in some standard.
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
