name       : perl-locale-codes
version    : 3.67
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/S/SB/SBECK/Locale-Codes-3.67.tar.gz : 13dde2bcc15f72b0d735182da99715cc55a67fac7c7e55ae2165c52a871726d3
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Locale::Language - module for dealing with language code sets
description: |
    Locale::Language - module for dealing with language code sets
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
