name       : perl-locale-codes
version    : '3.74'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/S/SB/SBECK/Locale-Codes-3.74.tar.gz : a310b4cad11d2708ab3d602724d16f5ef01362d57de57cb5e99e1221e9a16ecb
homepage   : https://metacpan.org/pod/Locale::Codes
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Locale::Language - module for dealing with language code sets
description: |
    Locale-Codes is a distribution containing a set of modules designed to work with sets of codes which uniquely identify something. For example, there are codes associated with different countries, different currencies, different languages, etc. These sets of codes are typically maintained in some standard.
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
